spring.application.name=portly
server.port=${SERVER_PORT:8080}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Jackson xd
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# LinkedIn OAuth
linkedin.client-id=${LINKEDIN_CLIENT_ID}
linkedin.client-secret=${LINKEDIN_CLIENT_SECRET}
linkedin.redirect-uri=${LINKEDIN_REDIRECT_URI:http://localhost:8080/auth/linkedin/callback}
linkedin.scope=openid profile email

# GitHub OAuth
github.client-id=${GITHUB_CLIENT_ID}
github.client-secret=${GITHUB_CLIENT_SECRET}
github.redirect-uri=${GITHUB_REDIRECT_URI:http://localhost:8080/auth/github/callback}

# Google OAuth
google.client-id=${GOOGLE_CLIENT_ID}
google.client-secret=${GOOGLE_CLIENT_SECRET}
google.redirect-uri=${GOOGLE_REDIRECT_URI:http://localhost:8080/auth/google/callback}

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-days=7

# Frontend
app.frontend-url=${FRONTEND_URL:https://portly-front.vercel.app}
